/** @type {import('tailwindcss').Config} */
export default {
    content: ["./resources/**/*.blade.php", "./resources/**/*.js"],
    theme: {
        extend: {
            fontFamily: {
                lato: ["Lato", "sans-serif"],
            },
        },
    },
    safelist: [
        "badge",
        "badge-secondary",
        "badge-primary",
        "badge-error",
        "badge-warning",
        "btn-success",
        "btn-error",

        // Datatable Tailwind CSS
        "grid grid-cols-1",
        "md:grid-cols-2",
        "self-center",
        "self-center",
        "place-self-end",
        "my-2",
        "col-span-2",
        "border",
        "border-gray-200",
        "rounded",
        "min-w-full",
        "bg-white",
        "self-center",
        "self-center",
        "place-self-end",
        "dataTables_wrapper",
        "dt-tailwindcss",
        "border",
        "placeholder-gray-500",
        "ml-2",
        "px-3",
        "py-2",
        "rounded-lg",
        "border-gray-200",
        "focus:border-blue-500",
        "focus:ring",
        "focus:ring-blue-500",
        "focus:ring-opacity-50",
        "border",
        "px-3",
        "py-2",
        "rounded-lg",
        "border-gray-200",
        "focus:border-blue-500",
        "focus:ring",
        "focus:ring-blue-500",
        "focus:ring-opacity-50",
        "dt-processing",
        "uk-panel",
        "font-semibold",
        "bg-gray-100",
        "bg-white",
        "relative",
        "inline-flex",
        "justify-center",
        "items-center",
        "space-x-2",
        "border",
        "px-4",
        "py-2",
        "-mr-px",
        "leading-6",
        "hover:z-10",
        "focus:z-10",
        "active:z-10",
        "border-gray-200",
        "active:border-gray-200",
        "active:shadow-none",
        "rounded-l-lg",
        "rounded-r-lg",
        "text-gray-800",
        "hover:text-gray-900",
        "hover:border-gray-300",
        "hover:shadow-sm",
        "focus:ring",
        "focus:ring-gray-300",
        "focus:ring-opacity-25",
        "text-gray-300",
        "dataTable",
        "min-w-full",
        "text-sm",
        "align-middle",
        "whitespace-nowrap",
        "border-b",
        "border-gray-100",
        "px-3",
        "py-4",
        "text-gray-900",
        "bg-gray-100/75",
        "font-semibold",
        "text-left",
        "even:bg-gray-50",
        "p-3",
        "even:bg-gray-50",
        "p-3",
        "text-left",
    ],
    darkMode: "class",
    plugins: [require("daisyui")],
    daisyui: {
        themes: ["winter"],
        darkTheme: "light",
        base: false,
    },
};
